### ISSUE TITLE
Migrate Documentation

### ISSUE THREAD

**Issue by andyluo03** [andyluo03/DiscoDB#20]
Our documentation is currently in README.md. As our codebase expands, we will eventually outgrow this. The transition may be very difficult with a large codebase. I would like to explore various options to host our documentation before this happens.

**Comment by adityakode** [comment]
Hi @andyluo03 !
I am interested in this. 
I think **_readthedocs_** would be a good option for documentation.
Would love to work on this

**Comment by andyluo03** [comment]
@adityakode This is definitely an option! How would we go about linking this to version control and hosting our web API? Also, feel free to join our contributing [discord](https://discord.gg/hKYgY7gp)

**Comment by andyluo03** [comment]
@adityakode I created docs using mkdocs. If you are still interested in helping contribute documentation as the project grows, please let me know!
